import type { Principal } from '@dfinity/principal';
export interface Doctor {
  'age' : bigint,
  'name' : string,
  'designation' : string,
  'email' : string,
  'address' : string,
  'gender' : string,
  'phone_number' : string,
  'department' : string,
  'registered_on' : Time,
  'doctor_id' : string,
  'qualification' : string,
}
export interface Employee {
  'contact' : string,
  'salary' : bigint,
  'date_of_joining' : string,
  'email' : string,
  'first_name' : string,
  'last_name' : string,
  'employee_id' : string,
}
export interface Notice {
  'notice' : string,
  'from' : string,
  'time_stamp' : Time,
}
export interface Patient {
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'patient_id' : string,
  'name' : string,
  'email' : string,
  'blood_group' : string,
  'address' : string,
  'gender' : string,
  'phone_number' : string,
  'registered_on' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'createDoctor' : (
      arg_0: string,
      arg_1: string,
      arg_2: string,
      arg_3: string,
      arg_4: bigint,
      arg_5: string,
      arg_6: string,
      arg_7: string,
      arg_8: string,
      arg_9: string,
    ) => Promise<undefined>,
  'createEmployee' : (
      arg_0: string,
      arg_1: string,
      arg_2: string,
      arg_3: string,
      arg_4: string,
      arg_5: bigint,
      arg_6: string,
    ) => Promise<undefined>,
  'createNotice' : (arg_0: string, arg_1: string) => Promise<undefined>,
  'createPatient' : (
      arg_0: string,
      arg_1: string,
      arg_2: string,
      arg_3: string,
      arg_4: bigint,
      arg_5: string,
      arg_6: string,
      arg_7: number,
      arg_8: number,
      arg_9: string,
    ) => Promise<undefined>,
  'deleteEmployee' : (arg_0: string) => Promise<undefined>,
  'getDoctorById' : (arg_0: string) => Promise<[] | [Doctor]>,
  'readDepartments' : () => Promise<Array<string>>,
  'readDoctors' : () => Promise<Array<Doctor>>,
  'readEmployees' : () => Promise<Array<Employee>>,
  'readNotices' : () => Promise<Array<Notice>>,
  'readPatients' : () => Promise<Array<Patient>>,
  'updateDoctor' : (
      arg_0: string,
      arg_1: Time,
      arg_2: string,
      arg_3: string,
      arg_4: string,
      arg_5: bigint,
      arg_6: string,
      arg_7: string,
      arg_8: string,
      arg_9: string,
      arg_10: string,
    ) => Promise<undefined>,
  'updateEmployee' : (
      arg_0: string,
      arg_1: string,
      arg_2: string,
      arg_3: string,
      arg_4: string,
      arg_5: bigint,
      arg_6: string,
    ) => Promise<undefined>,
  'updatePatient' : (
      arg_0: string,
      arg_1: Time,
      arg_2: string,
      arg_3: string,
      arg_4: string,
      arg_5: bigint,
      arg_6: string,
      arg_7: string,
      arg_8: number,
      arg_9: number,
      arg_10: string,
    ) => Promise<undefined>,
}
